apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: casf-kube-template
  title: Kubernetes
  description: CASF python template kube
  tags:
    - casf
    - kubernetes
spec:
  owner: web@example.com
  type: service
  parameters:
    - title: Fill in some steps
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
    - name: kubernetesCluster
      type: string
      description: The volume type to be used
      default: minikube
      enum:
        - minikube
        - prod-cluster

  steps:
    - id: publish
      name: Publish
      action: publish:namespace
      input:
        name: ${{ parameters.name }}
