apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: casf-kube-template
  title: Kubernetes
  description: CASF python template kube
  tags:
    - casf
    - kubernetes
spec:
  owner: web@example.com
  type: service
  parameters:
    - title: Fill in some steps
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
    - name: kubernetesCluster
      title: Kubernetes Cluster
      type: string
      enum:
        - dev-cluster
        - prod-cluster

  steps:
    - id: publish
      name: Publish
      action: publish:namespace
      input:
        name: ${{ parameters.name }}
  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
