apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: casf-python-template
  title: test 123
  description: CASF python template 
  tags:
    - casf
    - python
spec:
  owner: web@example.com
  type: service
  parameters:
    - title: Fill in some steps
      required:
        - name
        - owner
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group

    - title: Choose a location
      required:
        - repoUrl
        - dryRun
      properties:
        repoUrl:
          title: Organisation
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
        dryRun:
          title: Only perform a dry run, don't publish anything
          type: boolean
          default: false

  steps:
    - id: publish
      name: Publish
      action: publish:githubTeam
      input:
        allowedHosts:
          - github.com
        url: ${{ parameters.repoUrl | parseRepoUrl }
        values:
          projectName: ${{ parameters.name }}
          pythonVersion: ${{ parameters.version }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }
    
  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
